### ISSUE TITLE
no /usr/bin/python in RHEL8 - module fails

### ISSUE THREAD

**Issue by bengland2** [sadsfae/ansible-sshkeys#1]
When I run the playbook on a RHEL8.1 server Iin the Alias lab, I get this error below, but I never used to get it with RHEL8.0.   There is no python installed, either 2 or 3.   This breaks my automation and makes me do everything by hand.    Is there some way for ansible-playbook to avoid running python to do this and just give me password-less ssh access using the [raw module](https://docs.ansible.com/ansible/latest/modules/raw_module.html)?   Once I have that, I can do whatever commands are needed to further initialize the system from there.   

Suggestion: have the user specify the public key file to install, and just make ~/.ssh/authorized_keys equal to that using the raw module, and do nothing else.   Since we got the error below, ansible-playbook got into the system!   So it would work.

```
MSG:

The following modules failed to execute: setup

fatal: [e23-h17-740xd.alias.example]: FAILED! => {
    "ansible_facts": {},
    "changed": false,
    "failed_modules": {
        "setup": {
            "failed": true,
            "module_stderr": "Shared connection to e23-h17-740xd.alias.example.com closed.\r\n",
            "module_stdout": "/bin/sh: /usr/bin/python: No such file or directory\r\n",
            "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
            "rc": 127
        }
    }

[root@e23-h15-740xd ~]# which python
/usr/bin/which: no python in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

```

**Comment by bengland2** [comment]
This playbook works, and is sufficient to get user's ssh public key installed without python on the target system.    What do you think Will?   This seems simple and breaks the dependency trap.

```
[bengland@localhost ansible-sshkeys]$ cat raw.yml
---
#
# Ansible playbook to manage SSH keys
#

- hosts: servers
  gather_facts: no
  remote_user: root
  vars:
    ssh_public_key_file: ~/.ssh/id_rsa.pub
    ssh_auth_keys: ~/.ssh/authorized_keys
  tasks:
  - name: read default ssh public key
    local_action: command cat "{{ ssh_public_key_file }}"
    register: ssh_public_key

  - name: install public key in target account .ssh/authorized_keys
    raw: "echo {{ ssh_public_key.stdout_lines[0] }} > {{ ssh_auth_keys }}"

  - name: install python so rest of ansible works!
    raw: "dnf install -y python3 && ln -sv /usr/bin/python3 /usr/bin/python"

```
So for example if I run this:

```
ansible-playbook --ssh-common-args '-o StrictHostKeyChecking=no'   -i hosts -e ansible_ssh_pass=password raw.yml
```
Then I can run:
```
ansible all -u root -i hosts -m shell -a uptime
```
